// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"xll.com/go-000/Week04/cmd/serverd/server"
	"xll.com/go-000/Week04/internal/data"
	"xll.com/go-000/Week04/internal/service"
)

// Injectors from wire.go:

func InitializeGRPCServer() *server.GRPCServer {
	userRepository := data.NewUserMemoryRepository()
	userServer := service.NewUserService(userRepository)
	grpcServer := server.NewServer(userServer)
	return grpcServer
}
